name: Publish

on:
  push:
    branches: ["main"]
    tags: ["*.*.*"]
    paths-ignore: ["*.md"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4 # Install version declared in global.json
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_API_KEY: ${{ secrets.WORKLEAP_NUGET_API_KEY }}

  linearb:
    needs: [publish]
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: ${{ github.ref == 'refs/heads/main' && 'staging' || 'release' }}
    secrets: inherit
